---
- name: test os
  fail:
    msg: "OS {{ ansible_distribution }} (version: {{ ansible_distribution_major_version }}) not supported."
  when: ansible_distribution != 'Debian' and ansible_distribution_major_version|int < 9

- name: import requirements
  import_tasks: requirements.yml

- name: flush handlers
  meta: flush_handlers

- name: import python init
  import_tasks: python_init.yml

- name: import mayan install
  import_tasks: mayan_install.yml